"""Add user shift tracking fields

Revision ID: 62e9d1fb6959
Revises: 
Create Date: 2025-04-18 03:02:43.253777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62e9d1fb6959'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_sign_in', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('sign_in_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('sign_out_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('patients_seen', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('shift_start', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('shift_end', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('shift_end')
        batch_op.drop_column('shift_start')
        batch_op.drop_column('patients_seen')
        batch_op.drop_column('sign_out_time')
        batch_op.drop_column('sign_in_time')
        batch_op.drop_column('last_sign_in')

    # ### end Alembic commands ###
