"""Add new columns to HealthReading model

Revision ID: 68af3c9deb7d
Revises: 8a4be5153e43
Create Date: 2025-04-18 21:29:47.126523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68af3c9deb7d'
down_revision = '8a4be5153e43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_reading', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reading_type', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('temperature', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('heart_rate', sa.Float(), nullable=True))
        batch_op.alter_column('systolic',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('diastolic',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_reading', schema=None) as batch_op:
        batch_op.alter_column('diastolic',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('systolic',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.drop_column('heart_rate')
        batch_op.drop_column('temperature')
        batch_op.drop_column('reading_type')

    # ### end Alembic commands ###
