"""Add pulse field to HealthReading and update User model

Revision ID: 8a4be5153e43
Revises: 8db3ba463017
Create Date: 2025-04-18 12:59:24.806735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a4be5153e43'
down_revision = '8db3ba463017'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_reading', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pulse', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_reading', schema=None) as batch_op:
        batch_op.drop_column('pulse')

    # ### end Alembic commands ###
