"""Add remember_me column to user table

Revision ID: 8db3ba463017
Revises: 62e9d1fb6959
Create Date: 2025-04-18 08:07:30.346321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8db3ba463017'
down_revision = '62e9d1fb6959'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remember_me', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('remember_me')

    # ### end Alembic commands ###
